import { Router, type IRouter } from "express";
import healthRouter from "./health";
import businessRouter from "./business";
import categoriesRouter from "./categories";
import listingsRouter from "./listings";
import bookingsRouter from "./bookings";
import quotesRouter from "./quotes";
import analyticsRouter from "./analytics";
import customersRouter from "./customers";
import addonsRouter from "./addons";
import claimsRouter from "./claims";
import superadminRouter from "./superadmin";
import unitsRouter from "./units";
import adminTeamRouter from "./admin-team";
import signupRouter from "./signup";
import communicationsRouter from "./communications";
import auditRouter from "./audit";
import feedbackRouter from "./feedback";
import aiRouter from "./ai";
import contactCardsRouter from "./contact-cards";
import notificationsRouter from "./notifications";
import chatRouter from "./chat";

const router: IRouter = Router();

router.use(auditRouter);
router.use(healthRouter);
router.use(businessRouter);
router.use(categoriesRouter);
router.use(listingsRouter);
router.use(bookingsRouter);
router.use(quotesRouter);
router.use(analyticsRouter);
router.use(customersRouter);
router.use(addonsRouter);
router.use(claimsRouter);
router.use(superadminRouter);
router.use(unitsRouter);
router.use(adminTeamRouter);
router.use(signupRouter);
router.use(communicationsRouter);
router.use(feedbackRouter);
router.use(aiRouter);
router.use(contactCardsRouter);
router.use(notificationsRouter);
router.use(chatRouter);

export default router;
